DROP SCHEMA IF EXISTS `2605993489_TinyVideo`;

CREATE SCHEMA IF NOT EXISTS `2605993489_TinyVideo`;

USE `2605993489_TinyVideo`;

CREATE TABLE IF NOT EXISTS PRICE(
	PRICE_CODE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	PRICE_DESCRIPTION VARCHAR(255),
	PRICE_RENTFEE DECIMAL(6, 2),
	PRICE_DAILYLATEFEE DECIMAL(6, 2)
);

CREATE TABLE IF NOT EXISTS MOVIE(
	MOVIE_NUM INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MOVIE_TITLE VARCHAR(255),
    MOVIE_YEAR INT,
    MOVIE_COST DECIMAL(6, 2),
    MOVIE_GENRE VARCHAR(255),
    PRICE_CODE INT,
    FOREIGN KEY (PRICE_CODE) REFERENCES PRICE(PRICE_CODE)
);

ALTER TABLE MOVIE AUTO_INCREMENT = 1234;

CREATE TABLE IF NOT EXISTS VIDEO(
	VID_NUM INT PRIMARY KEY NOT NULL,
    VID_INDATE DATE,
    MOVIE_NUM INT,
    FOREIGN KEY (MOVIE_NUM) REFERENCES MOVIE(MOVIE_NUM)
);

CREATE TABLE IF NOT EXISTS MEMBERSHIP(
	MEM_NUM INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MEM_FNAME VARCHAR(255),
    MEM_LNAME VARCHAR(255),
    MEM_STREET VARCHAR(255),
    MEM_CITY VARCHAR(255),
    MEM_STATE CHAR(2),
    MEM_ZIP INT,
    MEM_BALANCE DECIMAL(6, 2)
);

ALTER TABLE MEMBERSHIP AUTO_INCREMENT = 102;


CREATE TABLE IF NOT EXISTS RENTAL(
	RENT_NUM INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    RENT_DATE DATE,
    MEM_NUM INT,
    FOREIGN KEY (MEM_NUM) REFERENCES MEMBERSHIP(MEM_NUM)
);

ALTER TABLE RENTAL AUTO_INCREMENT = 1001;


CREATE TABLE IF NOT EXISTS DETAILRENTAL(
	RENT_NUM INT NOT NULL,
    VID_NUM INT NOT NULL,
    DETAIL_FEE DECIMAL(6, 2),
    DETAIL_DUEDATE DATE,
    DETAIL_RETURNDATE DATE,
    DETAIL_DAILYLATEFEE DECIMAL(6, 2),
    PRIMARY KEY (RENT_NUM, VID_NUM),
    FOREIGN KEY (RENT_NUM) REFERENCES RENTAL(RENT_NUM),
    FOREIGN KEY (VID_NUM) REFERENCES VIDEO(VID_NUM)
);