CREATE DATABASE 2605993489_TinyVideo;

use 2605993489_TinyVideo;

CREATE TABLE MEMBERSHIP (
	MEM_NUM INT PRIMARY KEY AUTO_INCREMENT,
    MEM_FNAME VARCHAR(40),
    MEM_LNAME VARCHAR(40),
    MEM_STREET VARCHAR(100),
    MEM_CITY VARCHAR(40),
    MEM_STATE CHAR(2),
    MEM_ZIP INT,
    MEM_BALANCE INT
);

ALTER TABLE MEMBERSHIP AUTO_INCREMENT = 100;

CREATE TABLE RENTAL (
	RENT_NUM INT PRIMARY KEY AUTO_INCREMENT,
    RENT_DATE DATE,
    MEM_MUM INT
);

ALTER TABLE RENTAL AUTO_INCREMENT = 1000;

CREATE TABLE DETAILRENTAL (
	RENT_NUM INT,
    VID_NUM INT,
    DETAIL_FEE DOUBLE,
    DETAIL_DUEDATE DATE,
    DETAIL_RETURNDATE DATE,
    DETAIL_DAILYLATEFEE INT
);

CREATE TABLE VIDEO (
	VID_NUM INT,
    VID_INDATE DATE,
    MOVIE_NUM INT
);

CREATE TABLE MOVIE (
	MOVIE_NUM INT,
    MOVIE_NAME VARCHAR(75),
    MOVIE_YEAR INT,
	MOVIE_COST DOUBLE,
    MOVIE_GENRE VARCHAR(50),
    PRICE_CODE VARCHAR(5)
);

CREATE TABLE PRICE (
	PRICE_CODE INT PRIMARY KEY AUTO_INCREMENT,
    PRICE_DESCRIPTION VARCHAR(50),
    PRICE_RENTFEE DOUBLE,
    PRICE_DAILYLATEFEE DOUBLE
);